name: Pipeline

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Deploy to Github Pages
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
          registry-url: https://npm.pkg.github.com
          scope: '@tuuturu'
          persist-credentials: false
      - run: npm ci
        env:
          NODE_AUTH_TOKEN: ${{ secrets.JULIUS_TOKEN }}
      - run: npm run build
        env:
          NODE_ENV: production

      - name: Deploy to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@3.2.1
        with:
          ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: dist
